version: '3'

services:
  traefik-reverse:
    image: traefik:1.7.18
    container_name: traefik-reverse
    command:
      - "--api"
      - "--docker"
    ports:
      - 80:80
      - 1001:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
